name: Checkov Scan

on:
  push:
    branches:
      - staging

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov Scan
      run: checkov -d . -o junitxml